"""Convert an inferred ChartSpec + SPL into Splunk dashboard source.

Two output formats, both paste-able straight into Splunk:

- **Simple XML** — paste into a Classic dashboard's *Source* editor.
- **Dashboard Studio JSON** — paste into a Studio dashboard's *Source* editor.

Pure functions, no I/O. The SPL is embedded verbatim as the panel search.
"""

import json
from xml.sax.saxutils import escape

from app.api.schemas import ChartSpec, SplunkChartExport

# Default dashboard time range — emitted as a comment/note so users can adjust.
_DEFAULT_EARLIEST = "-24h@h"
_DEFAULT_LATEST = "now"

# ChartSpec.chart_type -> Simple XML charting.chart value.
# stacked_bar and the non-chart element types (single_value, gauge, heatmap)
# are handled specially below.
_SIMPLE_XML_CHART = {
    "line": "line",
    "area": "area",
    "bar": "bar",
    "column": "column",
    "stacked_bar": "column",
    "pie": "pie",
    "scatter": "scatter",
    "bubble": "bubble",
}

# ChartSpec.chart_type -> Dashboard Studio visualization type.
_STUDIO_VIZ = {
    "line": "splunk.line",
    "area": "splunk.area",
    "bar": "splunk.bar",
    "column": "splunk.column",
    "stacked_bar": "splunk.column",
    "pie": "splunk.pie",
    "scatter": "splunk.scatter",
    "bubble": "splunk.bubble",
    "single_value": "splunk.singlevalue",
    "gauge": "splunk.fillergauge",
    "heatmap": "splunk.table",
}


def _simple_xml(spl: str, spec: ChartSpec, notes: list[str]) -> str:
    title = escape(spec.title or "Setuq Chart")
    query = escape(spl)
    search_block = (
        "        <search>\n"
        f"          <query>{query}</query>\n"
        f"          <earliest>{_DEFAULT_EARLIEST}</earliest>\n"
        f"          <latest>{_DEFAULT_LATEST}</latest>\n"
        "        </search>"
    )

    ctype = spec.chart_type

    if ctype == "single_value":
        panel = (
            "      <single>\n"
            f"        <title>{title}</title>\n"
            f"{search_block}\n"
            '        <option name="rangeColors">["0x53a051","0xf8be34","0xdc4e41"]</option>\n'
            "      </single>"
        )
    elif ctype == "heatmap":
        # No native Classic heatmap viz — degrade to a table.
        notes.append(
            "Simple XML has no native heatmap visualization; exported as a table panel."
        )
        panel = (
            "      <table>\n"
            f"        <title>{title}</title>\n"
            f"{search_block}\n"
            '        <option name="count">20</option>\n'
            "      </table>"
        )
    else:
        options = []
        if ctype == "gauge":
            options.append('        <option name="charting.chart">radialGauge</option>')
        else:
            chart = _SIMPLE_XML_CHART[ctype]
            options.append(f'        <option name="charting.chart">{chart}</option>')
            if ctype == "stacked_bar":
                options.append(
                    '        <option name="charting.chart.stackMode">stacked</option>'
                )
        if spec.x_field:
            options.append(
                f'        <option name="charting.axisTitleX.text">{escape(spec.x_field)}</option>'
            )
        if spec.y_fields:
            options.append(
                f'        <option name="charting.axisTitleY.text">{escape(", ".join(spec.y_fields))}</option>'
            )
        opts_xml = "\n".join(options)
        panel = (
            "      <chart>\n"
            f"        <title>{title}</title>\n"
            f"{search_block}\n"
            f"{opts_xml}\n"
            "      </chart>"
        )

    return (
        '<dashboard version="1.1">\n'
        f"  <label>{title}</label>\n"
        '  <description>Generated by Setuq</description>\n'
        "  <row>\n"
        "    <panel>\n"
        f"{panel}\n"
        "    </panel>\n"
        "  </row>\n"
        "</dashboard>"
    )


def _studio_json(spl: str, spec: ChartSpec, notes: list[str]) -> str:
    viz_id = "viz_setuq_1"
    ds_id = "ds_setuq_1"
    ctype = spec.chart_type
    viz_type = _STUDIO_VIZ[ctype]
    if ctype == "heatmap":
        notes.append(
            "Dashboard Studio has no native heatmap visualization; exported as a table."
        )

    viz_options: dict = {}
    if ctype == "stacked_bar":
        viz_options["stackMode"] = "stacked"

    visualization = {
        "type": viz_type,
        "title": spec.title or "Setuq Chart",
        "dataSources": {"primary": ds_id},
    }
    if viz_options:
        visualization["options"] = viz_options

    definition = {
        "title": spec.title or "Setuq Chart",
        "description": "Generated by Setuq",
        "inputs": {},
        "defaults": {
            "dataSources": {
                "ds.search": {
                    "options": {
                        "queryParameters": {
                            "earliest": _DEFAULT_EARLIEST,
                            "latest": _DEFAULT_LATEST,
                        }
                    }
                }
            }
        },
        "visualizations": {viz_id: visualization},
        "dataSources": {
            ds_id: {
                "type": "ds.search",
                "options": {
                    "query": spl,
                    "queryParameters": {
                        "earliest": _DEFAULT_EARLIEST,
                        "latest": _DEFAULT_LATEST,
                    },
                },
                "name": "Setuq Search",
            }
        },
        "layout": {
            "type": "absolute",
            "options": {"width": 1200, "height": 600, "display": "auto"},
            "structure": [
                {
                    "item": viz_id,
                    "type": "block",
                    "position": {"x": 0, "y": 0, "w": 1200, "h": 600},
                }
            ],
            "globalInputs": [],
        },
    }
    return json.dumps(definition, indent=2)


def build_exports(spl: str, spec: ChartSpec) -> SplunkChartExport:
    """Build Simple XML + Dashboard Studio JSON source for a chart."""
    notes: list[str] = []
    simple_xml = _simple_xml(spl, spec, notes)
    studio_json = _studio_json(spl, spec, notes)
    return SplunkChartExport(
        simple_xml=simple_xml, studio_json=studio_json, notes=notes
    )
